version: "3.8"
services:
    dev-container-template:
        container_name: dev-container-template
        image: dev-container-template
        build:
            context: .
            dockerfile: Dockerfile

        # For attaching shells
        stdin_open: true # docker run -i
        tty: true        # docker run -t

        user: user