version: "3.8"
services:

    dev:
        container_name: dh-viewer-dev
        image: dh-viewer-dev-img
        build:
          context: .
          dockerfile: Dockerfile
          args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        env_file:
          - build.env
        volumes:
          - ../:/home/user/ws
        ports:
          - 3000:3000

        # For attaching shells
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        
        hostname: dh-viewer
        user: user