name: Deploy to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    environment: production
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x] # Found in .devcontainer dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build project
        run: npm run build
      
      - name: Run tests and produce reports
        run: npm test 

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: site-files
          path: ./build
  
  deploy-website:
    name: Deploy Website
    environment: production
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: site-files
        path: ./build

    - name: Deploy to prod
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: prod

# TODO: Set Up RTM
  # deploy-docs:
    # name: Deploy Documentation
    # runs-on: ubuntu-latest