name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run tests and produce report
      run: npm test